### ISSUE TITLE
Do not show "subscribe" link next to tests which have finished

### ISSUE THREAD

**Issue by timplunkett** [Lullabot/drupal_qa_notifier#4]
Just a little nice to have, to not clutter the issue page as much.
If this isn't trivial, don't bother.

**Comment by neclimdul** [comment]
tricky because it might be handy to subscribe to RTBC but green issues to get notified if something makes them fail.

**Comment by timplunkett** [comment]
Those get retested randomly, you'd have to happen to be at your computer when it is retested. I find this tool much more useful for just-posted patches... Could just be me.

**Comment by mglaman** [comment]
I didn't test the below, yet, but it might do the trick. I agree that it seems most likely this will be used for tracking patches first sent off, not re-tests (because, IMO, you wouldn't want to run a re-test and blow away those logs.)

```
var files = document.querySelectorAll('td.pift-retest div.pift-operations');
```

Edit: tested. Can test in Chrome by running the following on a D.o issue node

```
window.document.querySelectorAll('td.pift-retest div.pift-operations');
```
